name: Deploy CICD Todo App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # =========================
      # SETUP SSH
      # =========================
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh

          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

          ssh-keyscan -H ${{ secrets.VM_HOST }} >> ~/.ssh/known_hosts

      # =========================
      # TEST SSH CONNECTION
      # =========================
      - name: Test SSH Connection
        run: |
          ssh -i ~/.ssh/id_ed25519 \
            -o StrictHostKeyChecking=no \
            -o IdentitiesOnly=yes \
            ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} "echo CONNECTED"

      # =========================
      # DEPLOY APPLICATION
      # =========================
      - name: Deploy To Azure VM
        run: |
          ssh -i ~/.ssh/id_ed25519 \
            -o StrictHostKeyChecking=no \
            -o IdentitiesOnly=yes \
            ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} << 'EOF'

            cd ~/temp/cicd_react_django/To-Do-Application_CICD

            git pull origin main

            # FRONTEND
            cd frontend

            npm install
            npm run build

            sudo rm -rf /var/www/cicd_react_django_todo/*
            sudo cp -r build/* /var/www/cicd_react_django_todo/

            # BACKEND
            cd ../backend

            source venv/bin/activate

            pip install -r requirements.txt

            python manage.py migrate

            pkill gunicorn || true

            gunicorn config.wsgi:application \
              --bind 127.0.0.1:8012 \
              --workers 3 \
              --daemon

            sudo systemctl reload nginx

            echo "DEPLOYMENT SUCCESS"

          EOF